<?xml version="1.0" encoding="utf-8"?><Database Name="pubs" Class="MyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=pubs;Integrated Security=True" SettingsObjectName="ADO_WF_LinqToSQL.Properties.Settings" SettingsPropertyName="pubsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.authors" Member="authors">
    <Type Name="author">
      <Column Name="au_id" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="au_lname" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="au_fname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="contract" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.publishers" Member="publishers">
    <Type Name="publisher">
      <Column Name="pub_id" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pub_name" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.titleauthor" Member="titleauthors">
    <Type Name="titleauthor">
      <Column Name="au_id" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title_id" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="au_ord" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="royaltyper" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.titles" Member="titles">
    <Type Name="title">
      <Column Name="title_id" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title" Member="title1" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="pub_id" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="advance" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="royalty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ytd_sales" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="notes" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="pubdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="title_sale" Member="sales" ThisKey="title_id" OtherKey="title_id" Type="sale" />
    </Type>
  </Table>
  <Table Name="dbo.app_test" Member="app_tests">
    <Type Name="app_test">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="str" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="number1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="number2" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.sales" Member="sales">
    <Type Name="sale">
      <Column Name="stor_id" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ord_num" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ord_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="qty" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="payterms" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="title_id" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="title_sale" Member="title" ThisKey="title_id" OtherKey="title_id" Type="title" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.get_author" Method="get_author">
    <Parameter Name="st" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="n" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="get_authorResult">
      <Column Name="au_id" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="au_lname" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="au_fname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="contract" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.deltest" Method="deltest">
    <Parameter Name="id" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="n" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>