//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CarDatabase : DbContext
    {
        public CarDatabase()
            : base("name=CarDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<car> cars { get; set; }
        public virtual DbSet<carType> carTypes { get; set; }
        public virtual DbSet<person> people { get; set; }
    
        [DbFunction("CarDatabase", "GetCarsByLogin")]
        public virtual IQueryable<GetCarsByLogin_Result> GetCarsByLogin(string login)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetCarsByLogin_Result>("[CarDatabase].[GetCarsByLogin](@login)", loginParameter);
        }
    }
}
