//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_test
    {
        public int id { get; set; }
        public string str { get; set; }
        public Nullable<int> number1 { get; set; }
        public Nullable<int> number2 { get; set; }
    }
}
