//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class pubsEntities : DbContext
    {
        public pubsEntities()
            : base("name=pubsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> authors { get; set; }
        public virtual DbSet<publisher> publishers { get; set; }
        public virtual DbSet<title> titles { get; set; }
        public virtual DbSet<app_test> app_test { get; set; }
    
        [DbFunction("pubsEntities", "GetAuthorsByState")]
        public virtual IQueryable<GetAuthorsByState_Result> GetAuthorsByState(string st)
        {
            var stParameter = st != null ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetAuthorsByState_Result>("[pubsEntities].[GetAuthorsByState](@st)", stParameter);
        }
    
        public virtual int AddAuthor(string au_id, string au_fname, string au_lname, string phone, string state, Nullable<bool> contract)
        {
            var au_idParameter = au_id != null ?
                new ObjectParameter("au_id", au_id) :
                new ObjectParameter("au_id", typeof(string));
    
            var au_fnameParameter = au_fname != null ?
                new ObjectParameter("au_fname", au_fname) :
                new ObjectParameter("au_fname", typeof(string));
    
            var au_lnameParameter = au_lname != null ?
                new ObjectParameter("au_lname", au_lname) :
                new ObjectParameter("au_lname", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var contractParameter = contract.HasValue ?
                new ObjectParameter("contract", contract) :
                new ObjectParameter("contract", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddAuthor", au_idParameter, au_fnameParameter, au_lnameParameter, phoneParameter, stateParameter, contractParameter);
        }
    }
}
