#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pubs")]
	public partial class pubsDB : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertowners(owners instance);
    partial void Updateowners(owners instance);
    partial void Deleteowners(owners instance);
    partial void Insertcars(cars instance);
    partial void Updatecars(cars instance);
    partial void Deletecars(cars instance);
    #endregion
		
		public pubsDB() : 
				base(global::Main.Properties.Settings.Default.pubsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public pubsDB(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pubsDB(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pubsDB(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pubsDB(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<owners> owners
		{
			get
			{
				return this.GetTable<owners>();
			}
		}
		
		public System.Data.Linq.Table<cars> cars
		{
			get
			{
				return this.GetTable<cars>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCars", IsComposable=true)]
		public object GetCars([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string own_id)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), own_id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetColumns")]
		public ISingleResult<GetColumnsResult> GetColumns([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string table_catalog, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string table_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), table_catalog, table_name);
			return ((ISingleResult<GetColumnsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTables")]
		public ISingleResult<GetTablesResult> GetTables([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string table_catalog)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), table_catalog);
			return ((ISingleResult<GetTablesResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.owners")]
	public partial class owners : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _own_id;
		
		private string _pathImg;
		
		private string _name;
		
		private string _address;
		
		private string _phone;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onown_idChanging(string value);
    partial void Onown_idChanged();
    partial void OnpathImgChanging(string value);
    partial void OnpathImgChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    #endregion
		
		public owners()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_own_id", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string own_id
		{
			get
			{
				return this._own_id;
			}
			set
			{
				if ((this._own_id != value))
				{
					this.Onown_idChanging(value);
					this.SendPropertyChanging();
					this._own_id = value;
					this.SendPropertyChanged("own_id");
					this.Onown_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pathImg", DbType="VarChar(100)")]
		public string pathImg
		{
			get
			{
				return this._pathImg;
			}
			set
			{
				if ((this._pathImg != value))
				{
					this.OnpathImgChanging(value);
					this.SendPropertyChanging();
					this._pathImg = value;
					this.SendPropertyChanged("pathImg");
					this.OnpathImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(20)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cars")]
	public partial class cars : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _car_id;
		
		private string _pathImg;
		
		private string _brand;
		
		private string _body_type;
		
		private string _registrDate;
		
		private string _own_id;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncar_idChanging(string value);
    partial void Oncar_idChanged();
    partial void OnpathImgChanging(string value);
    partial void OnpathImgChanged();
    partial void OnbrandChanging(string value);
    partial void OnbrandChanged();
    partial void Onbody_typeChanging(string value);
    partial void Onbody_typeChanged();
    partial void OnregistrDateChanging(string value);
    partial void OnregistrDateChanged();
    partial void Onown_idChanging(string value);
    partial void Onown_idChanged();
    #endregion
		
		public cars()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_id", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string car_id
		{
			get
			{
				return this._car_id;
			}
			set
			{
				if ((this._car_id != value))
				{
					this.Oncar_idChanging(value);
					this.SendPropertyChanging();
					this._car_id = value;
					this.SendPropertyChanged("car_id");
					this.Oncar_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pathImg", DbType="VarChar(100)")]
		public string pathImg
		{
			get
			{
				return this._pathImg;
			}
			set
			{
				if ((this._pathImg != value))
				{
					this.OnpathImgChanging(value);
					this.SendPropertyChanging();
					this._pathImg = value;
					this.SendPropertyChanged("pathImg");
					this.OnpathImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand", DbType="VarChar(50)")]
		public string brand
		{
			get
			{
				return this._brand;
			}
			set
			{
				if ((this._brand != value))
				{
					this.OnbrandChanging(value);
					this.SendPropertyChanging();
					this._brand = value;
					this.SendPropertyChanged("brand");
					this.OnbrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_body_type", DbType="VarChar(50)")]
		public string body_type
		{
			get
			{
				return this._body_type;
			}
			set
			{
				if ((this._body_type != value))
				{
					this.Onbody_typeChanging(value);
					this.SendPropertyChanging();
					this._body_type = value;
					this.SendPropertyChanged("body_type");
					this.Onbody_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registrDate", DbType="VarChar(20)")]
		public string registrDate
		{
			get
			{
				return this._registrDate;
			}
			set
			{
				if ((this._registrDate != value))
				{
					this.OnregistrDateChanging(value);
					this.SendPropertyChanging();
					this._registrDate = value;
					this.SendPropertyChanged("registrDate");
					this.OnregistrDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_own_id", DbType="VarChar(20)")]
		public string own_id
		{
			get
			{
				return this._own_id;
			}
			set
			{
				if ((this._own_id != value))
				{
					this.Onown_idChanging(value);
					this.SendPropertyChanging();
					this._own_id = value;
					this.SendPropertyChanged("own_id");
					this.Onown_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetColumnsResult
	{
		
		private string _COLUMN_NAME;
		
		public GetColumnsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN_NAME", DbType="NVarChar(128)")]
		public string COLUMN_NAME
		{
			get
			{
				return this._COLUMN_NAME;
			}
			set
			{
				if ((this._COLUMN_NAME != value))
				{
					this._COLUMN_NAME = value;
				}
			}
		}
	}
	
	public partial class GetTablesResult
	{
		
		private string _TABLE_NAME;
		
		public GetTablesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_NAME", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TABLE_NAME
		{
			get
			{
				return this._TABLE_NAME;
			}
			set
			{
				if ((this._TABLE_NAME != value))
				{
					this._TABLE_NAME = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
