//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDirData", ReplyAction="http://tempuri.org/IService1/GetDirDataResponse")]
        string[] GetDirData(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDirData", ReplyAction="http://tempuri.org/IService1/GetDirDataResponse")]
        System.Threading.Tasks.Task<string[]> GetDirDataAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStreamData", ReplyAction="http://tempuri.org/IService1/GetStreamDataResponse")]
        System.IO.Stream GetStreamData(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStreamData", ReplyAction="http://tempuri.org/IService1/GetStreamDataResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetStreamDataAsync(string address);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Main.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Main.ServiceReference1.IService1>, Main.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetDirData(string address) {
            return base.Channel.GetDirData(address);
        }
        
        public System.Threading.Tasks.Task<string[]> GetDirDataAsync(string address) {
            return base.Channel.GetDirDataAsync(address);
        }
        
        public System.IO.Stream GetStreamData(string address) {
            return base.Channel.GetStreamData(address);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetStreamDataAsync(string address) {
            return base.Channel.GetStreamDataAsync(address);
        }
    }
}
