//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars
    {
        public string car_id { get; set; }
        public string pathImg { get; set; }
        public string brand { get; set; }
        public string body_type { get; set; }
        public string registrDate { get; set; }
        public string own_id { get; set; }
    }
}
