//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowAuthorsBooks
    {
        public string au_id { get; set; }
        public string au_fname { get; set; }
        public string au_lname { get; set; }
        public string title { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
