//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class author
    {
        public string au_id { get; set; }

        [Display(Name = "Last name")]
        [Required(ErrorMessage = "You need to specify the last name")]
        public string au_lname { get; set; }

        [Display(Name = "First name")]
        [Required(ErrorMessage = "You need to specify the first name")]
        public string au_fname { get; set; }
        public string phone { get; set; }
        public string address { get; set; }

        [Required(ErrorMessage = "You need to specify the city")]
        [MaxLength(10, ErrorMessage = "City name is too long!")]
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public Nullable<bool> contract { get; set; }
        public string photo { get; set; }
    }
}
