<?xml version="1.0" encoding="utf-8"?><Database Name="ADO_EXAM02" Class="DepEmplDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=ADO_EXAM02;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="Main.Properties.Settings" SettingsPropertyName="ADO_EXAM02ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Departments" Member="Departments">
    <Type Name="Departments">
      <Column Name="DepartmentId" Type="System.String" DbType="VarChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HeadId" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employees">
      <Column Name="Employee_id" Type="System.String" DbType="VarChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="PhotoPath" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DepartmentsEmployees" Member="DepartmentsEmployees">
    <Type Name="DepartmentsEmployees">
      <Column Name="DepartmentId" Type="System.String" DbType="VarChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmployeeId" Type="System.String" DbType="VarChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.GetEmployeesWithDepartmentTitle" Method="GetEmployeesWithDepartmentTitle">
    <ElementType Name="GetEmployeesWithDepartmentTitleResult">
      <Column Name="FirstName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>